### ISSUE TITLE
doc: Update the CONTRIBUTING.md file

### ISSUE THREAD

**Issue by ShubhAgarwal-dev** [oss2019/InstituteFormsPortal#3]
Please enhance this document with instructions for contributing catering to both OSS members and external collaborators. Additionally, once the workflow is established, incorporate guidelines for development, building, and testing.

**Comment by shishirkj** [comment]
hi can i work on this?

**Comment by ShubhAgarwal-dev** [comment]
Certainly, feel free to comment "I want to attempt" on the issue you're interested in contributing to. Once you've done so, I'll assign that particular issue to you as requested.

**Comment by ShubhAgarwal-dev** [comment]
done
