### ISSUE TITLE
dev: add the database schema in schema.prisma file

### ISSUE THREAD

**Issue by ShubhAgarwal-dev** [oss2019/InstituteFormsPortal#5]
Please add the database described in this [schema](https://github.com/oss2019/InstituteFormsPortal#table-structure) to the [schema.prisma](https://github.com/oss2019/InstituteFormsPortal/blob/main/prisma/schema.prisma) file.

**Comment by V-Mokhun** [comment]
Hey, I'd like to work on your issue so please consider assigning me to it
